normal:
  left: cursor::move_left
  right: cursor::move_right
  up: cursor::move_up
  down: cursor::move_down
  ctrl-c: app::exit
  i: app::to_insert_mode
  ':': app::to_command_mode
  a: 
    - app::to_insert_mode
    - cursor::move_right
  shift-A: 
    - app::to_insert_mode
    - cursor::move_to_end_of_line
  shift-I: 
    - app::to_insert_mode
    - cursor::move_to_start_of_line
  backspace: cursor::move_left
  escape: normal::reset
  shift-L: cursor::move_to_end_of_line
  shift-H: cursor::move_to_start_of_line
  shift-T: monitor::scroll_to_first_line
  shift-B: monitor::scroll_to_last_line
  shift-G: normal::move_to_target_line
  shift-O: 
    - cursor::move_to_start_of_line
    - buffer::new_line
  o: 
    - cursor::move_to_end_of_line
    - buffer::new_line
    - cursor::move_down
  j: normal::move_down_n
  k: normal::move_up_n
  h: normal::move_left_n
  l: normal::move_right_n
  d: app::to_delete_mode
  w: app::to_workspace_mode
  /: app::to_search_mode
  n: normal::move_to_next_words
  b: normal::move_to_prev_words
  e: normal::move_to_next_words_end
  u: buffer::undo
  ctrl-r: buffer::redo
  num: normal::count_cmd
  shift-R: app::to_replace_mode
insert:
  escape: app::to_normal_mode
  left: cursor::move_left
  right: cursor::move_right
  up: cursor::move_up
  down: cursor::move_down
  ctrl-c: app::exit
  ctrl-s: buffer::save_file
  ctrl-z: buffer::undo
  enter: 
    - buffer::new_line
    - cursor::move_down
    - cursor::move_to_start_of_line
  backspace: insert::backspace
  tab: buffer::insert_tab
  _: 
    - buffer::insert_char
command:
  escape: command::to_normal_mode
  backspace: command::backspace
  enter: command::commit_and_execute
  _:
    - command::insert_command

workspace:
  up: workspace::move_up
  down: workspace::move_down
  enter: workspace::enter
  escape: workspace::to_normal_mode
  ctrl-c: app::exit
search:
  /:
  - search::clear 
  - app::to_search_mode
  backspace: search::backspace
  escape: 
  - search::clear
  - app::to_normal_mode
  enter: search::exec_search
  up: search::last_result
  down: search::next_result
  ctrl-c: app::exit
  _:  search::input_search_data
delete:
  ctrl-c: app::exit
  escape: app::to_normal_mode
  w: 
    - delete::delete_words
    - app::to_normal_mode
  d: 
    - delete::delete_lines
    - cursor::move_to_start_of_line
    - app::to_normal_mode

replace:
  escape: app::to_normal_mode
  left: cursor::move_left
  right: cursor::move_right
  up: cursor::move_up
  down: cursor::move_down
  ctrl-c: app::exit
  ctrl-s: workspace::save_file
  ctrl-z: workspace::undo
  enter: 
    - buffer::new_line
    - cursor::move_down
    - cursor::move_to_start_of_line
  backspace: insert::backspace
  tab: buffer::insert_tab
  _: 
    - buffer::insert_char_on_replace