normal:
  left: cursor::move_left
  right: cursor::move_right
  up: cursor::move_up
  down: cursor::move_down
  ctrl-c: app::exit
  i: app::to_insert_mode
  a: 
    - app::to_insert_mode
    - cursor::move_right
  shift-A: 
    - app::to_insert_mode
    - cursor::move_to_end_of_line
  shift-I: 
    - app::to_insert_mode
    - cursor::move_to_start_of_line
  backspace: cursor::move_left
  escape: normal::reset
  shift-L: cursor::move_to_end_of_line
  shift-H: cursor::move_to_start_of_line
  shift-T: monitor::scroll_to_first_line
  shift-B: monitor::scroll_to_last_line
  shift-G: normal::move_to_target_line
  j: normal::move_down_n
  k: normal::move_up_n
  h: normal::move_left_n
  l: normal::move_right_n
  d: 
    - normal::transition
    - normal::delete_some
  w: app::to_workspace_mode
  _: normal::transition
insert:
  escape: app::to_normal_mode
  left: cursor::move_left
  right: cursor::move_right
  up: cursor::move_up
  down: cursor::move_down
  ctrl-c: app::exit
  ctrl-s: workspace::save_file
  ctrl-z: workspace::undo
  enter: 
    - buffer::new_line
    - cursor::move_down
    - cursor::move_to_start_of_line
  backspace: insert::backspace
  tab: buffer::insert_tab
  _: 
    - buffer::insert_char
workspace:
  up: workspace::move_up
  down: workspace::move_down
  enter: workspace::enter
  escape: workspace::to_normal_mode
  ctrl-c: app::exit