normal:
  left: cursor::move_left
  right: cursor::move_right
  up: cursor::move_up
  down: cursor::move_down
  ctrl-c: app::exit
  i: app::to_insert_mode
  backspace: cursor::move_left
  w: app::to_workspace_mode
  /: app::to_search_mode
insert:
  escape: app::to_normal_mode
  left: cursor::move_left
  right: cursor::move_right
  up: cursor::move_up
  down: cursor::move_down
  ctrl-c: app::exit
  ctrl-s: workspace::save_file
  ctrl-z: workspace::undo
  enter: 
    - buffer::new_line
    - cursor::move_down
    - cursor::move_to_start_of_line
  backspace: insert::backspace
  tab: buffer::insert_tab
  _: 
    - buffer::insert_char
workspace:
  up: workspace::move_up
  down: workspace::move_down
  enter: workspace::enter
  escape: workspace::to_normal_mode
  ctrl-c: app::exit
search:
  /:
  - search::clear 
  - app::to_search_mode
  backspace: search::backspace
  escape: 
  - search::clear
  - app::to_normal_mode
  enter: search::exec_search
  up: search::last_result
  down: search::next_result
  ctrl-c: app::exit
  _:  search::input_search_data